;;; tjp-mode.el --- Major mode for editing TaskJuggler files -*- lexical-binding: t; -*-

;; Copyright (C) 2025 TaskJuggler Developers

;; Author: TaskJuggler Developers <taskjuggler-devel@googlegroups.com>
;; Keywords: languages, project management
;; Version: 2.2.0
;; Package-Requires: ((emacs "27.1"))
;; URL: https://github.com/jackhale98/tjp-mode

;; The keyword lists were originally generated by TaskJuggler's
;; EmacsLispSyntax.rb and have been checked against `tj3man'.
;; Features: tag navigation, ID completion, context help, advanced folding,
;; include navigation, dependency visualization, resource allocation tracking,
;; macro expansion, validation, and project statistics

;;; Commentary:

;; This major mode provides comprehensive support for editing TaskJuggler 3
;; project files (.tjp, .tji).
;;
;; Features:
;; - Comprehensive syntax highlighting for all TJ3 keywords
;; - Intelligent indentation
;; - Advanced code folding (hideshow-mode)
;; - Tag navigation with xref (M-. to jump to definitions)
;; - imenu integration for quick navigation
;; - ID completion at point with company-mode support
;; - eldoc integration (shows hierarchical IDs)
;; - Context-sensitive help (tj3man integration)
;; - Enhanced error navigation with flycheck support
;; - Integration with tj3 compiler (via compile command)
;; - Include file navigation
;; - Date/time insertion helpers
;; - Hierarchical structure browser
;; - Macro expansion and navigation
;; - Dependency visualization
;; - Resource allocation display
;; - Live syntax validation
;; - Project statistics
;; - Comment handling
;; - Optional whitespace cleanup on save
;;
;; Installation:
;;   git clone https://github.com/jackhale98/tjp-mode.git
;;   (add-to-list 'load-path "/path/to/tjp-mode")
;;   (require 'tjp-mode)
;;   ;; .tjp and .tji files auto-activate - no auto-mode-alist entry needed
;;
;;   Evil, Doom and Spacemacs users get `SPC m' (or `,') bindings
;;   automatically: `tjp-mode' loads `tjp-evil' when it is on the load
;;   path, and that file does nothing unless evil is present.  See the
;;   README for straight.el, elpaca, package-vc and Doom recipes.
;;
;; Key Bindings:
;;   C-c C-c     - Compile project
;;   C-c C-v     - Compile and view HTML
;;   C-c C-k     - Validate buffer syntax
;;   M-.         - Jump to task/resource definition
;;   M-,         - Pop back from definition
;;   C-c C-j     - Jump to include file
;;   C-c C-n     - Next block
;;   C-c C-p     - Previous block
;;   C-c C-f     - Toggle folding at point
;;   C-c C-a     - Fold all blocks
;;   C-c C-o     - Unfold all blocks
;;   C-c C-i     - Insert task template
;;   C-c C-r     - Insert resource template
;;   C-c C-d     - Insert date
;;   C-c C-s     - Show structure browser
;;   C-c C-t     - Generate tags file
;;   C-c C-=     - Show project statistics
;;   C-c C-h     - Documentation for the keyword at point (tj3man)
;;   C-c C-y     - Show the dependency chain of the task at point
;;   C-c C-l     - Show resource allocations
;;
;; Multi-file projects:
;;   tj3 only accepts a master `.tjp' file, so when editing an included
;;   `.tji' point the mode at the project it belongs to:
;;
;;     ;; .dir-locals.el
;;     ((tjp-mode . ((tjp-project-file . "project.tjp"))))
;;
;;   For Doom Emacs users: Use SPC m (localleader) for all commands
;;   See configuration example in the README.

;;; Code:

(require 'xref)
(require 'imenu)
(require 'eldoc)
(require 'hideshow)
(require 'outline)
(require 'compile)
(require 'cl-lib)

(declare-function org-read-date "org" (&optional with-time to-time from-string prompt))
(declare-function define-auto-insert "autoinsert" (condition action &optional after))
(defvar projectile-project-root-files)

;; Customization Group
;; ============================================================================

(defgroup tjp nil
  "Major mode for editing TaskJuggler files."
  :group 'languages
  :prefix "tjp-")

(defcustom tjp-indent-offset 2
  "Number of spaces for each indentation level in TaskJuggler mode."
  :type 'integer
  :safe 'integerp
  :group 'tjp)

(defcustom tjp-man-command "tj3man"
  "Command to run TaskJuggler man pages."
  :type 'string
  :group 'tjp)

(defcustom tjp-compiler-command "tj3"
  "Command to compile TaskJuggler files."
  :type 'string
  :group 'tjp)

(defcustom tjp-auto-validate nil
  "When non-nil, automatically validate buffer after save."
  :type 'boolean
  :group 'tjp)

;; Helper Functions for Shell Execution
;; ============================================================================

(defvar tjp--command-cache (make-hash-table :test 'equal)
  "Memoized results of `tjp--resolve-command', keyed by command name.")

(defun tjp--ask-login-shell (command)
  "Ask the user's login shell for the absolute path of COMMAND.
Returns nil when the shell cannot find it.  A GUI Emacs typically does
not inherit the PATH exported by the user's shell startup files, and
this is the one place the mode pays for a login shell - the answer is
cached, so it happens at most once per command per session."
  (let ((shell (or (getenv "SHELL") shell-file-name)))
    (when (and shell (file-executable-p shell))
      (with-temp-buffer
        (when (eq 0 (ignore-errors
                      (call-process shell nil t nil "-lc"
                                    (format "command -v %s"
                                            (shell-quote-argument command)))))
          ;; A login shell may print a banner first; the answer is the last
          ;; non-empty line it wrote.
          (let* ((lines (split-string (buffer-string) "\n" t "[ \t\r]+"))
                 (path (car (last lines))))
            (and path (file-executable-p path) path)))))))

(defun tjp--resolve-command (command)
  "Return the absolute path of COMMAND, or nil if it cannot be found."
  (let ((cached (gethash command tjp--command-cache 'missing)))
    (if (not (eq cached 'missing))
        cached
      (puthash command
               (or (and (file-name-absolute-p command)
                        (file-executable-p command)
                        command)
                   (executable-find command)
                   (tjp--ask-login-shell command))
               tjp--command-cache))))

;; Keyword Lists
;; ============================================================================

(defconst tjp-properties
  '("account"
    "accountreport"
    "export"
    "icalreport"
    "nikureport"
    "resource"
    "resourcereport"
    "scenario"
    "shift"
    "statussheetreport"
    "tagfile"
    "task"
    "taskreport"
    "textreport"
    "timesheetreport"
    "tracereport")
  "TaskJuggler property keywords (top-level constructs).")

(defconst tjp-attributes
  '("accountprefix"
    "accountroot"
    "active"
    "activetasks"
    "adopt"
    "aggregate"
    "alert"
    "alertlevels"
    "alertmessages"
    "alertsummaries"
    "alerttrend"
    "allocate"
    "alternative"
    "annualleave"
    "annualleavebalance"
    "annualleavelist"
    "author"
    "auxdir"
    "balance"
    "booking"
    "bsi"
    "caption"
    "cellcolor"
    "celltext"
    "center"
    "charge"
    "chargeset"
    "chart"
    "children"
    "closedtasks"
    "columns"
    "competitorcount"
    "competitors"
    "complete"
    "completed"
    "copyright"
    "cost"
    "credits"
    "criticalness"
    "currency"
    "currencyformat"
    "daily"
    "dailymax"
    "dailymin"
    "dailyworkinghours"
    "date"
    "definitions"
    "depends"
    "details"
    "directreports"
    "disabled"
    "duration"
    "duties"
    "efficiency"
    "effort"
    "effortdone"
    "effortleft"
    "email"
    "enabled"
    "end"
    "endcredit"
    "epilog"
    "extend"
    "fail"
    "flags"
    "followers"
    "fontcolor"
    "footer"
    "formats"
    "freetime"
    "freework"
    "fte"
    "gapduration"
    "gaplength"
    "gauge"
    "halign"
    "hasalert"
    "headcount"
    "header"
    "headline"
    "height"
    "hideaccount"
    "hidejournalentry"
    "hidereport"
    "hideresource"
    "hidetask"
    "hierarchindex"
    "hourly"
    "id"
    "index"
    "inherit"
    "inputs"
    "interval1"
    "interval2"
    "interval3"
    "interval4"
    "isactive"
    "ischildof"
    "isdependencyof"
    "isdutyof"
    "isfeatureof"
    "isleaf"
    "ismilestone"
    "isongoing"
    "isresource"
    "isresponsibilityof"
    "istask"
    "isvalid"
    "journal"
    "journal_sub"
    "journalattributes"
    "journalentry"
    "journalmessages"
    "journalmode"
    "journalsummaries"
    "leaveallowance"
    "leaveallowances"
    "leaves"
    "left"
    "length"
    "limits"
    "line"
    "listitem"
    "listtype"
    "loadunit"
    "managers"
    "mandatory"
    "markdate"
    "maxend"
    "maximum"
    "maxstart"
    "milestone"
    "minend"
    "minimum"
    "minstart"
    "monthly"
    "monthlymax"
    "monthlymin"
    "name"
    "navigator"
    "newtask"
    "no"
    "note"
    "novevents"
    "now"
    "number"
    "numberformat"
    "onend"
    "onstart"
    "opennodes"
    "opentasks"
    "outputdir"
    "overtime"
    "pathcriticalness"
    "period"
    "persistent"
    "precedes"
    "precursors"
    "priority"
    "projectid"
    "projectids"
    "projection"
    "prolog"
    "purge"
    "quarterly"
    "rate"
    "rawhtmlhead"
    "reference"
    "remaining"
    "replace"
    "reportprefix"
    "reports"
    "resourceattributes"
    "resourceprefix"
    "resourceroot"
    "resources"
    "responsible"
    "revenue"
    "richtext"
    "right"
    "rollupaccount"
    "rollupresource"
    "rolluptask"
    "scale"
    "scenario"
    "scenarios"
    "scenariospecific"
    "scheduled"
    "scheduling"
    "schedulingmode"
    "select"
    "selfcontained"
    "seqno"
    "shift"
    "shifts"
    "shorttimeformat"
    "sickleave"
    "sloppy"
    "sortaccounts"
    "sortjournalentries"
    "sortresources"
    "sorttasks"
    "specialleave"
    "start"
    "startcredit"
    "status"
    "statussheet"
    "summary"
    "targets"
    "task"
    "taskattributes"
    "taskprefix"
    "taskroot"
    "text"
    "timeformat"
    "timeformat1"
    "timeformat2"
    "timeoff"
    "timesheet"
    "timezone"
    "timingresolution"
    "title"
    "tooltip"
    "trackingscenario"
    "treelevel"
    "turnover"
    "unpaidleave"
    "vacation"
    "warn"
    "wbs"
    "weekly"
    "weeklymax"
    "weeklymin"
    "weekstartsmonday"
    "weekstartssunday"
    "width"
    "work"
    "workinghours"
    "yearly"
    "yearlyworkingdays")
  "TaskJuggler attribute keywords.")

(defconst tjp-special-keywords
  '("macro" "project" "supplement" "include")
  "Special TaskJuggler keywords.")

(defconst tjp--all-keywords
  (delete-dups
   (append tjp-special-keywords tjp-properties tjp-attributes))
  "All TaskJuggler keywords offered for completion at point.")

(defconst tjp-block-keywords
  '("account"
    "accountreport"
    "allocate"
    "booking"
    "columns"
    "dailymax"
    "dailymin"
    "date"
    "depends"
    "export"
    "extend"
    "icalreport"
    "include"
    "journalentry"
    "limits"
    "macro"
    "maximum"
    "minimum"
    "monthlymax"
    "monthlymin"
    "navigator"
    "newtask"
    "nikureport"
    "number"
    "precedes"
    "project"
    "reference"
    "resource"
    "resourcereport"
    "richtext"
    "scenario"
    "shift"
    "status"
    "statussheet"
    "statussheetreport"
    "tagfile"
    "task"
    "taskreport"
    "text"
    "textreport"
    "timesheet"
    "timesheetreport"
    "tracereport"
    "weeklymax"
    "weeklymin")
  "Keywords that can contain blocks with curly braces.")

(defconst tjp--report-keywords
  '("taskreport" "resourcereport" "textreport" "accountreport"
    "icalreport" "tracereport" "statussheetreport" "timesheetreport"
    "nikureport" "tagfile" "export")
  "Report-defining keywords in TaskJuggler.")

(defconst tjp-structural-keywords
  '("account"
    "accountreport"
    "export"
    "icalreport"
    "macro"
    "nikureport"
    "project"
    "resource"
    "resourcereport"
    "scenario"
    "shift"
    "statussheetreport"
    "supplement"
    "tagfile"
    "task"
    "taskreport"
    "textreport"
    "timesheetreport"
    "tracereport")
  "Keywords that introduce a top level or nested property definition.
These are the blocks `tjp-next-block' and `tjp-previous-block' move
between; attribute keywords such as `allocate' or `columns' are
deliberately excluded.")

;; Font Lock Configuration
;; ============================================================================

(defconst tjp-font-lock-keywords
  (let* ((properties-regexp (regexp-opt tjp-properties 'words))
         (attributes-regexp (regexp-opt tjp-attributes 'words))
         (special-regexp (regexp-opt tjp-special-keywords 'words)))
    `(
      ;; Comments and strings (including -8<- ... ->8- blocks) are handled
      ;; syntactically, by the syntax table and `tjp-syntax-propertize'.

      ;; Dates: YYYY-MM-DD or YYYY-MM-DD-HH:MM
      (,"\\<[0-9]\\{4\\}-[0-9]\\{1,2\\}-[0-9]\\{1,2\\}\\(?:-[0-9]\\{1,2\\}:[0-9]\\{1,2\\}\\(?::[0-9]\\{1,2\\}\\)?\\(?:-[-+]?[0-9]\\{4\\}\\)?\\)?\\>" . font-lock-constant-face)

      ;; Times: HH:MM or HH:MM:SS
      (,"\\<[0-9]\\{1,2\\}:[0-9]\\{2\\}\\(?::[0-9]\\{2\\}\\)?\\>" . font-lock-constant-face)

      ;; Numbers with optional units: 123, 123.45, 123d, 123h, 123w, 123m, 123y, 123min
      (,"\\<[-+]?[0-9]+\\(?:\\.[0-9]+\\)?\\(?:[hdwmy]\\|min\\)?\\>" . font-lock-constant-face)

      ;; Macro variables: ${...}
      (,"\\${[^}]*}" . font-lock-variable-name-face)

      ;; Include statements
      (,"\\<include\\s-+.*$" . font-lock-preprocessor-face)

      ;; Special keywords (macro, project, supplement)
      (,special-regexp . font-lock-preprocessor-face)

      ;; Properties (task, resource, report types)
      (,properties-regexp . font-lock-function-name-face)

      ;; Attributes
      (,attributes-regexp . font-lock-keyword-face)))
  "Font lock keywords for TaskJuggler mode.")

;; Syntax Table
;; ============================================================================

(defvar tjp-mode-syntax-table
  (let ((st (make-syntax-table)))
    ;; Comments
    (modify-syntax-entry ?# "<" st)   ; # starts a comment
    (modify-syntax-entry ?\n ">" st)  ; newline ends a comment
    (modify-syntax-entry ?/ ". 124" st) ; / can start // or /* comments
    (modify-syntax-entry ?* ". 23b" st) ; * is part of /* */ comments

    ;; Strings.  TaskJuggler also accepts single-quoted strings, but treating
    ;; ' as a string delimiter would break on the apostrophes that occur in
    ;; ordinary prose, so it stays punctuation and 'foo' is not highlighted.
    ;; Multi-line -8<- ... ->8- strings are handled by `tjp-syntax-propertize'.
    (modify-syntax-entry ?\" "\"" st)
    (modify-syntax-entry ?' "." st)

    ;; Operators and punctuation
    (modify-syntax-entry ?{ "(}" st)
    (modify-syntax-entry ?} "){" st)
    (modify-syntax-entry ?\[ "(]" st)
    (modify-syntax-entry ?\] ")[" st)

    ;; Word constituents
    (modify-syntax-entry ?_ "_" st)
    ;; TaskJuggler IDs are [a-zA-Z_]\w* and never contain a hyphen, so `-'
    ;; is punctuation: as a symbol constituent it would make
    ;; `thing-at-point' return whole dates such as 2026-01-31 as the
    ;; "identifier" at point, which xref, eldoc and tj3man all choke on.
    (modify-syntax-entry ?- "." st)
    (modify-syntax-entry ?. "_" st) ; Allow dots in identifiers (for hierarchical IDs)

    st)
  "Syntax table for `tjp-mode'.")

;; Syntax Propertization
;; ============================================================================

(defun tjp--put-syntax (beg end syntax)
  "Give the text between BEG and END the syntax class SYNTAX."
  (put-text-property beg end 'syntax-table (string-to-syntax syntax)))

(defun tjp--propertize-scissors (open-pos)
  "Mark the scissors string starting at OPEN-POS as a generic string.
OPEN-POS is the position of the first character of the `-8<-' mark.  The
opening and closing marks are included in the string so that nothing
inside the block is parsed as code.  Point is left after the block."
  (tjp--put-syntax open-pos (1+ open-pos) "|")
  (goto-char (1+ open-pos))
  (if (re-search-forward "->8\\(-\\)" nil t)
      (progn
        (tjp--put-syntax (match-beginning 1) (match-end 1) "|")
        (goto-char (match-end 1)))
    (goto-char (point-max))))

(defun tjp--balanced-p (beg end regexp open-char)
  "Return non-nil if the delimiters matched by REGEXP balance between BEG and END.
OPEN-CHAR is the character that opens a nesting level."
  (let ((depth 0))
    (save-excursion
      (goto-char beg)
      (while (re-search-forward regexp end t)
        (setq depth (+ depth (if (eq (char-before) open-char) 1 -1)))))
    (zerop depth)))

(defun tjp--neutralize (beg end regexp)
  "Give every match of REGEXP between BEG and END punctuation syntax."
  (save-excursion
    (goto-char beg)
    (while (re-search-forward regexp end t)
      (tjp--put-syntax (match-beginning 0) (match-end 0) "."))))

(defun tjp--propertize-macro-body (open-pos)
  "Neutralize unbalanced brackets in the macro body opened at OPEN-POS.
Macro bodies routinely contain half of a block (that is what makes them
useful), and those stray braces would otherwise be counted as real
nesting by `syntax-ppss' and shift the indentation of everything that
follows.  Balanced bodies are left alone so that they still indent
naturally.  Point is left after the body."
  (let* ((body-beg (1+ open-pos))
         (body-end (save-excursion
                     (goto-char body-beg)
                     (if (re-search-forward "\\][ \t]*$" nil t)
                         (match-beginning 0)
                       (point-max)))))
    (unless (tjp--balanced-p body-beg body-end "[{}]" ?{)
      (tjp--neutralize body-beg body-end "[{}]"))
    (unless (tjp--balanced-p body-beg body-end "[][]" ?\[)
      (tjp--neutralize body-beg body-end "[][]"))
    (goto-char (min (point-max) (1+ body-end)))))

(defconst tjp--syntax-propertize-rules
  (syntax-propertize-rules
   ;; Scissors string.  Per the TJ3 scanner the opening mark must be the
   ;; last thing on its line.
   ("\\(-\\)8<-[ \t]*$"
    (1 (ignore (tjp--propertize-scissors (match-beginning 1)))))
   ;; macro NAME [ ... ]
   ("^[ \t]*macro[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*\\(\\[\\)"
    (1 (ignore (tjp--propertize-macro-body (match-beginning 1))))))
  "Syntax propertization rules for `tjp-mode'.")

(defun tjp-syntax-propertize (start end)
  "Apply TaskJuggler syntax properties between START and END."
  (goto-char start)
  (funcall tjp--syntax-propertize-rules start end))

;; Indentation
;; ============================================================================

(defun tjp--in-string-or-comment-p (&optional pos)
  "Return non-nil if POS (default point) is inside a string or comment.
Point and the match data are preserved: this is called from the middle
of search loops, and `syntax-ppss' may run `syntax-propertize', which
moves point and performs searches of its own."
  (save-excursion
    (save-match-data
      (nth 8 (syntax-ppss (or pos (point)))))))

(defun tjp--in-string-p (&optional pos)
  "Return non-nil if POS (default point) is inside a string.
Guarded like `tjp--in-string-or-comment-p'."
  (save-excursion
    (save-match-data
      (nth 3 (syntax-ppss (or pos (point)))))))

(defun tjp--nesting-depth (&optional pos)
  "Return the bracket nesting depth at POS (default point)."
  (save-excursion
    (save-match-data
      (car (syntax-ppss (or pos (point)))))))

(defun tjp--calculate-indent ()
  "Return the column the current line should be indented to.
Indentation is derived from the brace/bracket nesting depth reported by
`syntax-ppss', so it is robust to blank lines, multi-brace lines and
arbitrary nesting.  A line that begins with a closing brace is dedented
one level so it lines up with the construct that opened it.  Returns nil
for a line that lies inside a multi-line string, whose layout is
significant to tj3 and must not be rewritten."
  (save-excursion
    (beginning-of-line)
    (unless (tjp--in-string-or-comment-p (point))
      (let ((depth (tjp--nesting-depth (point))))
        (when (looking-at "[ \t]*[]}]")
          (setq depth (1- depth)))
        (* (max 0 depth) tjp-indent-offset)))))

(defun tjp-indent-line ()
  "Indent current line as TaskJuggler code.
Lines inside a `-8<- ... ->8-' string are left untouched: their
indentation is part of the string value."
  (interactive)
  (let ((indent (tjp--calculate-indent)))
    (cond
     ((null indent) 'noindent)
     ;; Point is in the leading whitespace: reindent and land on the text.
     ((<= (current-column) (current-indentation))
      (indent-line-to indent))
     ;; Point is inside the text: keep it there while fixing indentation.
     (t (save-excursion (indent-line-to indent))))))

;; ============================================================================
;; TAG NAVIGATION & XREF BACKEND
;; ============================================================================

(defcustom tjp-project-file nil
  "The master `.tjp' file this buffer belongs to, or nil for the buffer itself.
tj3 only accepts a project file whose name ends in `.tjp', so an include
file cannot be compiled or checked on its own.  Set this - typically in
`.dir-locals.el' - to the master project file and `tjp-compile',
`tjp-compile-and-view' and `tjp-validate-buffer' will act on it.  It is
also the file that ID scanning starts from, so IDs defined anywhere in
the project become available to xref and completion:

  ;; .dir-locals.el
  ((tjp-mode . ((tjp-project-file . \"project.tjp\"))))

A relative name is looked for in the current file's directory and then
in each directory above it."
  :type '(choice (const :tag "This buffer" nil) (file :tag "Project file"))
  :safe 'stringp
  :group 'tjp)

(defcustom tjp-follow-includes t
  "When non-nil, xref and completion scan transitively `include'd files.
This lets you jump to and complete task/resource IDs defined in other
files of a multi-file TaskJuggler project."
  :type 'boolean
  :group 'tjp)

(defcustom tjp-cache-ttl 2.0
  "Seconds a scan of the project is reused before it is refreshed.
The scan is redone immediately whenever the buffer changes; this only
bounds how long a stale scan of unchanged `include'd files can survive."
  :type 'number
  :group 'tjp)

(defvar-local tjp--xref-cache nil
  "Cache of task/resource definitions for the xref backend and completion.")

(defvar-local tjp--xref-cache-state nil
  "State the cache in `tjp--xref-cache' was built from.
A cons of the buffer's modification tick and the time of the scan.")

(defvar tjp--file-scan-cache (make-hash-table :test 'equal)
  "Memoized scans of on-disk included files.
Keyed by truename; each value is (MTIME . SCAN), where SCAN is the result
of `tjp--scan-defs-in-buffer'.  Files open in a live buffer are never
memoized here so unsaved edits are always reflected.")

(defconst tjp--definition-regexp
  (concat "^[ \t]*\\(task\\|resource\\|account\\|macro\\|shift\\|scenario\\)[ \t]+"
          ;; In TaskJuggler the ID is optional (`task \"Name\" { ... }' is
          ;; legal and gets a generated ID) and the name is mandatory, except
          ;; for macros, which have an ID and no name.
          "\\(?:\\([A-Za-z_][A-Za-z0-9_]*\\)[ \t]*\\)?"
          "\\(?:\"\\([^\"]*\\)\"[ \t]*\\)?"
          ;; Macro bodies open with `[', other blocks with `{', and a
          ;; definition may also carry no block at all or open it on the
          ;; following line.
          "\\(?:[][{]\\|$\\)")
  "Regexp matching a property definition header.
Group 1 is the keyword, group 2 the optional ID, group 3 the optional name.")

(defun tjp--prepare-scan-buffer ()
  "Give the current temporary buffer just enough of `tjp-mode' to be scanned."
  (set-syntax-table tjp-mode-syntax-table)
  (setq-local parse-sexp-lookup-properties t)
  (setq-local syntax-propertize-function #'tjp-syntax-propertize))

(defun tjp--scan-defs-in-buffer (file)
  "Scan the current buffer for definitions and includes.
Returns (DEFS . INCLUDES).  DEFS is a list of
\(ID TYPE LINE COL POS FILE NAME) entries, where ID is nil for a
definition written without one and NAME is nil for a macro.  INCLUDES is
a list of absolute paths of `include'd files resolved relative to FILE's
directory."
  (let ((defs '())
        (includes '())
        (dir (file-name-directory (or file ""))))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward tjp--definition-regexp nil t)
        (let* ((id (match-string-no-properties 2))
               (anchor (or (match-beginning 2) (match-beginning 1))))
          (unless (tjp--in-string-or-comment-p (match-beginning 1))
            (push (list id
                        (match-string-no-properties 1)
                        (line-number-at-pos anchor)
                        (save-excursion (goto-char anchor) (current-column))
                        anchor
                        file
                        (match-string-no-properties 3))
                  defs))))
      (goto-char (point-min))
      (while (re-search-forward "^[ \t]*include[ \t]+\"\\([^\"]+\\)\"" nil t)
        (unless (tjp--in-string-or-comment-p (match-beginning 0))
          (push (expand-file-name (match-string-no-properties 1) dir) includes))))
    (cons (nreverse defs) (nreverse includes))))

(defun tjp--scan-file (file)
  "Return (DEFS . INCLUDES) for FILE.
Uses the live buffer if FILE is being visited; otherwise reads it from
disk, memoizing the scan by modification time in `tjp--file-scan-cache'."
  (let ((buf (find-buffer-visiting file)))
    (if buf
        (with-current-buffer buf (tjp--scan-defs-in-buffer file))
      (let* ((abs (file-truename file))
             (mtime (file-attribute-modification-time (file-attributes file)))
             (cached (gethash abs tjp--file-scan-cache)))
        (if (and cached (equal (car cached) mtime))
            (cdr cached)
          (let ((scan (with-temp-buffer
                        (tjp--prepare-scan-buffer)
                        (insert-file-contents file)
                        (tjp--scan-defs-in-buffer file))))
            (puthash abs (cons mtime scan) tjp--file-scan-cache)
            scan))))))

(defun tjp--collect-all-defs (file visited)
  "Recursively collect definitions from FILE following `include's.
VISITED is a hash table of already-scanned truenames for cycle detection."
  (let ((abs (file-truename file)))
    (when (and (file-readable-p file) (not (gethash abs visited)))
      (puthash abs t visited)
      (let ((scan (tjp--scan-file file)))
        (append (car scan)
                (mapcan (lambda (inc) (tjp--collect-all-defs inc visited))
                        (cdr scan)))))))

(defun tjp--project-file ()
  "Return the master project file for this buffer.
That is `tjp-project-file' when set, and the visited file otherwise.  A
relative `tjp-project-file' is looked for in the buffer's directory and
then in each directory above it, so one `.dir-locals.el' at the root of
the project works for includes in subdirectories."
  (if (and tjp-project-file (not (string-empty-p tjp-project-file)))
      (if (file-name-absolute-p tjp-project-file)
          tjp-project-file
        (let* ((dir (if buffer-file-name
                        (file-name-directory buffer-file-name)
                      default-directory))
               (name tjp-project-file)
               (root (locate-dominating-file
                      dir
                      (lambda (candidate)
                        (file-exists-p (expand-file-name name candidate))))))
          (expand-file-name name (or root dir))))
    buffer-file-name))

(defun tjp--collect-defs ()
  "Scan the project and return every definition that carries an ID."
  (let* ((root (tjp--project-file))
         (visited (make-hash-table :test 'equal))
         (defs (when (and tjp-follow-includes root (file-readable-p root))
                 (tjp--collect-all-defs root visited))))
    ;; Always add this buffer's own definitions.  It may be an include file
    ;; the master does not reach, or may not have been saved yet.
    (unless (and buffer-file-name
                 (gethash (file-truename buffer-file-name) visited))
      (setq defs (append (car (tjp--scan-defs-in-buffer buffer-file-name))
                         defs)))
    ;; Definitions without an ID cannot be referenced, so they are not
    ;; navigation targets; `imenu' and the structure browser still list them.
    (seq-filter #'car defs)))

(defun tjp--update-xref-cache (&optional force)
  "Make sure `tjp--xref-cache' is current, rescanning the project if needed.
The scan is reused while the buffer is unmodified and less than
`tjp-cache-ttl' seconds old, which keeps completion cheap in large
projects.  With FORCE non-nil, always rescan."
  (let ((tick (buffer-chars-modified-tick))
        (now (float-time)))
    (when (or force
              (null tjp--xref-cache-state)
              (/= (car tjp--xref-cache-state) tick)
              (> (- now (cdr tjp--xref-cache-state)) tjp-cache-ttl))
      (setq tjp--xref-cache (tjp--collect-defs))
      (setq tjp--xref-cache-state (cons tick now)))
    tjp--xref-cache))

(defun tjp--get-id-at-point ()
  "Get the hierarchical ID at point (e.g., `project.phase.task')."
  (let ((bounds (bounds-of-thing-at-point 'symbol)))
    (when bounds
      (buffer-substring-no-properties (car bounds) (cdr bounds)))))

(defun tjp--find-id-in-cache (id)
  "Find ID in the xref cache, resolving hierarchical references.
An exact match wins.  Otherwise `a.b.c' resolves to the definition of
its last component, and a query resolves to a definition whose own ID
ends in `.ID'.  A bare suffix match is deliberately not accepted: `ev'
must not silently resolve to `dev'."
  (when (and id (not (string-empty-p id)))
    (or (cl-find id tjp--xref-cache :key #'car :test #'string=)
        (let ((leaf (car (last (split-string id "\\." t)))))
          (and leaf (not (string= leaf id))
               (cl-find leaf tjp--xref-cache :key #'car :test #'string=)))
        (cl-find-if (lambda (entry)
                      (string-suffix-p (concat "." id) (car entry)))
                    tjp--xref-cache))))

(defun tjp-xref-backend ()
  "TaskJuggler xref backend function."
  'tjp)

(cl-defmethod xref-backend-identifier-at-point ((_backend (eql tjp)))
  "Return the identifier at point."
  (tjp--get-id-at-point))

(cl-defmethod xref-backend-definitions ((_backend (eql tjp)) identifier)
  "Find definitions of IDENTIFIER."
  (tjp--update-xref-cache)
  (let ((entry (tjp--find-id-in-cache identifier)))
    (when entry
      (cl-destructuring-bind (id type line col _pos file &optional name) entry
        (list (xref-make (if name
                             (format "%s %s \"%s\"" type id name)
                           (format "%s %s" type id))
                         (xref-make-file-location file line col)))))))

(cl-defmethod xref-backend-identifier-completion-table ((_backend (eql tjp)))
  "Return completion table for identifiers."
  (tjp--update-xref-cache)
  (mapcar #'car tjp--xref-cache))

;; ============================================================================
;; IMENU SUPPORT
;; ============================================================================

(defconst tjp--index-regexp
  (concat "^[ \t]*\\("
          (regexp-opt (append '("task" "resource" "account" "macro")
                              tjp--report-keywords))
          "\\)[ \t]+"
          "\\(?:\\([A-Za-z_][A-Za-z0-9_]*\\)[ \t]*\\)?"
          "\\(?:\"\\([^\"]*\\)\"[ \t]*\\)?"
          "\\(?:[][{]\\|$\\)")
  "Regexp matching anything worth listing in `imenu' or the structure browser.
Group 1 is the keyword, group 2 the optional ID, group 3 the optional name.")

(defun tjp--definition-label (id name)
  "Return a display label for a definition with ID and NAME, either may be nil."
  (cond ((and id name) (format "%s (%s)" id name))
        (id id)
        (name (format "\"%s\"" name))
        (t "<unnamed>")))

(defun tjp--imenu-create-index ()
  "Create imenu index for TaskJuggler buffer.
Definitions written without an ID - which TaskJuggler allows, since only
the name is mandatory - are listed under their name."
  (let ((index-alist '())
        (tasks '())
        (resources '())
        (accounts '())
        (reports '())
        (macros '()))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward tjp--index-regexp nil t)
        (let* ((type (match-string-no-properties 1))
               (id (match-string-no-properties 2))
               (name (match-string-no-properties 3))
               (label (tjp--definition-label id name))
               (pos (match-beginning 0)))
          (unless (tjp--in-string-or-comment-p pos)
            (cond
             ((string= type "task")
              (push (cons label pos) tasks))
             ((string= type "resource")
              (push (cons label pos) resources))
             ((string= type "account")
              (push (cons label pos) accounts))
             ((string= type "macro")
              (push (cons label pos) macros))
             ((member type tjp--report-keywords)
              (push (cons label pos) reports)))))))

    (when tasks
      (push (cons "Tasks" (nreverse tasks)) index-alist))
    (when resources
      (push (cons "Resources" (nreverse resources)) index-alist))
    (when accounts
      (push (cons "Accounts" (nreverse accounts)) index-alist))
    (when macros
      (push (cons "Macros" (nreverse macros)) index-alist))
    (when reports
      (push (cons "Reports" (nreverse reports)) index-alist))

    (nreverse index-alist)))

;; ============================================================================
;; ELDOC SUPPORT (Show hierarchical ID in minibuffer)
;; ============================================================================

(defun tjp--get-hierarchical-id ()
  "Get the full hierarchical ID of the current task/resource."
  (save-excursion
    (let ((ids '())
          (current-level 999))
      (while (and (> (point) (point-min))
                  (re-search-backward
                   "^\\s-*\\(task\\|resource\\|account\\)\\s-+\\([a-zA-Z0-9_.]+\\)"
                   nil t))
        (let ((indent (current-indentation))
              (id (match-string 2)))
          (when (< indent current-level)
            (push id ids)
            (setq current-level indent))))
      (when ids
        (mapconcat #'identity ids ".")))))

(defun tjp--on-definition-id-p ()
  "Return non-nil if point is on the ID of a definition line.
A definition line is one introduced by task/resource/account/macro."
  (save-excursion
    (let ((pt (point)))
      (beginning-of-line)
      (and (re-search-forward
            "\\s-*\\(?:task\\|resource\\|account\\|macro\\)\\s-+\\([a-zA-Z0-9_.]+\\)"
            (line-end-position) t)
           (>= pt (match-beginning 1))
           (<= pt (match-end 1))))))

(defun tjp-eldoc-function (&rest _)
  "Provide eldoc documentation for TaskJuggler."
  (let ((keyword (tjp--get-id-at-point)))
    (cond
     ;; Show keyword type when point is over a known keyword.
     ((and keyword (member keyword tjp-properties))
      (format "Property: %s" keyword))
     ((and keyword (member keyword tjp-attributes))
      (format "Attribute: %s" keyword))
     ;; Only show the hierarchical ID when point is on the definition's ID,
     ;; otherwise this would shadow the keyword hints above everywhere below
     ;; the first task in the file.
     ((tjp--on-definition-id-p)
      (let ((hier-id (tjp--get-hierarchical-id)))
        (when hier-id
          (format "Hierarchical ID: %s" hier-id))))
     (t nil))))

;; ============================================================================
;; ID COMPLETION AT POINT (with company-mode support)
;; ============================================================================

(defun tjp-completion-at-point ()
  "Completion at point for TaskJuggler keywords and known IDs."
  (let ((bounds (or (bounds-of-thing-at-point 'symbol)
                    (cons (point) (point)))))
    (unless (tjp--in-string-or-comment-p (car bounds))
      (tjp--update-xref-cache)
      (let ((collection (append (mapcar #'car tjp--xref-cache)
                                tjp--all-keywords)))
        (when collection
          (list (car bounds)
                (cdr bounds)
                collection
                :annotation-function
                (lambda (cand)
                  (let ((entry (tjp--find-id-in-cache cand)))
                    (cond
                     (entry (format " <%s>" (cadr entry)))
                     ((member cand tjp-properties) " <property>")
                     ((member cand tjp-special-keywords) " <keyword>")
                     ((member cand tjp-attributes) " <attribute>"))))
                :company-docsig
                (lambda (cand)
                  (let ((entry (tjp--find-id-in-cache cand)))
                    (when entry
                      (format "%s [Line %d]" (cadr entry) (caddr entry)))))
                :exclusive 'no))))))

;; ============================================================================
;; CONTEXT-SENSITIVE HELP (tj3man integration)
;; ============================================================================

(defun tjp--help-keyword ()
  "Return the keyword to document: the one at point, or one read from the user."
  (let ((at-point (tjp--get-id-at-point)))
    (if (member at-point tjp--all-keywords)
        at-point
      (completing-read "TJ3 keyword: " tjp--all-keywords nil nil
                       (and at-point
                            (string-match-p "\\`[a-z][a-z0-9]*\\'" at-point)
                            at-point)))))

(defun tjp-show-help (&optional keyword)
  "Show TaskJuggler documentation for KEYWORD, or the keyword at point.
Falls back to the online manual when `tjp-man-command' cannot be found."
  (interactive)
  (let* ((keyword (or keyword (tjp--help-keyword)))
         (program (tjp--resolve-command tjp-man-command)))
    (if program
        (let ((buffer (get-buffer-create "*tj3man*")))
          (with-current-buffer buffer
            (let ((inhibit-read-only t))
              (erase-buffer)
              ;; --silent drops the eight line version banner.
              (call-process program nil t nil "--silent" keyword)
              (goto-char (point-min)))
            (help-mode))
          (display-buffer buffer))
      (browse-url (format "https://taskjuggler.org/tj3/manual/%s.html" keyword)))))

;; ============================================================================
;; ADVANCED FOLDING SUPPORT
;; ============================================================================

(defun tjp-setup-hideshow ()
  "Configure hideshow-mode for TaskJuggler."
  ;; Remove any existing tjp-mode entry first
  (setq hs-special-modes-alist
        (assq-delete-all 'tjp-mode hs-special-modes-alist))
  ;; Add our configuration.  Both kinds of block are foldable: `{ ... }' for
  ;; properties and reports, `[ ... ]' for macro bodies.
  (add-to-list 'hs-special-modes-alist
               '(tjp-mode
                 "[[{]"        ; Block start
                 "[]}]"        ; Block end
                 "#\\|//"       ; Comment start
                 nil           ; forward-sexp-func
                 nil)))        ; adjust-beg-func

(defun tjp--block-opener-position ()
  "Return the position of the block opener governing point, or nil.
That is the `{' or `[' later on the current line if there is one - so
that point on a definition header folds that definition - and otherwise
the innermost bracket point is inside of.  Brackets in comments and
strings are ignored, since `syntax-ppss' does the looking."
  (save-excursion
    (let ((eol (line-end-position))
          (opener nil))
      (save-excursion
        (while (and (not opener)
                    (re-search-forward "[[{]" eol t))
          (unless (tjp--in-string-or-comment-p (1- (point)))
            (setq opener (1- (point))))))
      (or opener (save-match-data (nth 1 (syntax-ppss)))))))

(defun tjp-toggle-fold ()
  "Toggle folding of the block at or around point."
  (interactive)
  (if (not (bound-and-true-p hs-minor-mode))
      (message "Hideshow mode not enabled")
    (condition-case err
        (if (cl-some (lambda (ov) (eq (overlay-get ov 'invisible) 'hs))
                     (overlays-at (point)))
            (hs-show-block)
          (let ((opener (tjp--block-opener-position)))
            (if (not opener)
                (message "No block found at point")
              (save-excursion
                (goto-char opener)
                (hs-toggle-hiding)))))
      (error
       (message "Error toggling fold: %s" (error-message-string err))))))

(defun tjp-fold-all ()
  "Fold all blocks in the buffer (brace-aware)."
  (interactive)
  (if (bound-and-true-p hs-minor-mode)
      (hs-hide-all)
    (message "Hideshow mode not enabled")))

(defun tjp-unfold-all ()
  "Unfold all blocks in the buffer."
  (interactive)
  (if (bound-and-true-p hs-minor-mode)
      (hs-show-all)
    (message "Hideshow mode not enabled")))

;; ============================================================================
;; ENHANCED ERROR NAVIGATION
;; ============================================================================

(defvar tjp-error-regexp-alist
  '((tjp-error "^\\([^:]+\\):\\([0-9]+\\): Error: \\(.*\\)$" 1 2 nil 2 1)
    (tjp-warning "^\\([^:]+\\):\\([0-9]+\\): Warning: \\(.*\\)$" 1 2 nil 1 1)
    (tjp-info "^\\([^:]+\\):\\([0-9]+\\): Info: \\(.*\\)$" 1 2 nil 0 1))
  "Regexp patterns for TaskJuggler error messages.")

(defun tjp-setup-compilation ()
  "Setup compilation mode for TaskJuggler."
  (add-to-list 'compilation-error-regexp-alist-alist
               '(tjp-error "^\\([^:]+\\):\\([0-9]+\\): Error:" 1 2 nil 2 1))
  (add-to-list 'compilation-error-regexp-alist-alist
               '(tjp-warning "^\\([^:]+\\):\\([0-9]+\\): Warning:" 1 2 nil 1 1))
  (add-to-list 'compilation-error-regexp-alist-alist
               '(tjp-info "^\\([^:]+\\):\\([0-9]+\\): Info:" 1 2 nil 0 1))

  (add-to-list 'compilation-error-regexp-alist 'tjp-error)
  (add-to-list 'compilation-error-regexp-alist 'tjp-warning)
  (add-to-list 'compilation-error-regexp-alist 'tjp-info))

;; Optional: Flycheck integration (if flycheck is available)
(defvar tjp--flycheck-defined nil
  "Non-nil once the tjp flycheck checker has been defined.")

(defun tjp-setup-flycheck ()
  "Define a flycheck checker for TaskJuggler, once, if flycheck is loaded.
The checker runs on the saved file rather than on a temporary copy: tj3
rejects any name that does not end in `.tjp' and resolves `include's
relative to the file's own directory, so a copy in a temporary directory
could not be checked."
  (when (and (not tjp--flycheck-defined)
             (featurep 'flycheck)
             (fboundp 'flycheck-define-command-checker))
    (setq tjp--flycheck-defined t)
    (funcall 'flycheck-define-command-checker 'tjp
             "A TaskJuggler syntax checker using tj3."
             :command '((eval (or (tjp--resolve-command tjp-compiler-command)
                                  tjp-compiler-command))
                        "--silent" "--no-color" "--check-syntax"
                        (eval (tjp--project-file)))
             :error-patterns
             '((error line-start (file-name) ":" line ": Error: " (message) line-end)
               (warning line-start (file-name) ":" line ": Warning: " (message) line-end)
               (info line-start (file-name) ":" line ": Info: " (message) line-end))
             :predicate (lambda ()
                          (let ((file (tjp--project-file)))
                            (and file
                                 (string-suffix-p ".tjp" file)
                                 (file-exists-p file)
                                 (not (buffer-modified-p)))))
             :modes '(tjp-mode))
    (when (boundp 'flycheck-checkers)
      (add-to-list 'flycheck-checkers 'tjp))))

;; ============================================================================
;; TAGFILE GENERATION
;; ============================================================================

(defun tjp--etags-section (file)
  "Return the TAGS section describing FILE, or nil when it defines nothing.
`etags' has no TaskJuggler support, so the table is written from this
mode's own scan, in the format `etags.el' expects."
  (with-temp-buffer
    (tjp--prepare-scan-buffer)
    (insert-file-contents file)
    (let ((entries '()))
      (goto-char (point-min))
      (while (re-search-forward tjp--index-regexp nil t)
        (let ((id (match-string-no-properties 2))
              (bol (line-beginning-position)))
          (when (and id (not (tjp--in-string-or-comment-p (match-beginning 1))))
            (push (format "%s\177%s\001%d,%d\n"
                          (buffer-substring-no-properties bol (match-end 2))
                          id
                          (line-number-at-pos (match-beginning 1))
                          (1- (position-bytes bol)))
                  entries))))
      (when entries
        (let ((body (apply #'concat (nreverse entries))))
          (format "\f\n%s,%d\n%s" file (string-bytes body) body))))))

(defun tjp-generate-tags ()
  "Write an Emacs TAGS table for this project and visit it.
Note that `M-.' already works without a tags table: `tjp-mode' provides
an xref backend that indexes the project directly.  This command is for
tools outside Emacs, or for including TaskJuggler IDs in a table shared
with other languages."
  (interactive)
  (let* ((project (or (tjp--project-file)
                      (user-error "Buffer is not visiting a file; save it first")))
         (tags-file (expand-file-name "TAGS" (file-name-directory project)))
         (sections (delq nil (mapcar #'tjp--etags-section (tjp--project-files)))))
    (if (null sections)
        (message "No TaskJuggler definitions found")
      (with-temp-file tags-file
        (apply #'insert sections))
      (visit-tags-table tags-file)
      (message "Wrote %s (%d file%s)" tags-file (length sections)
               (if (= 1 (length sections)) "" "s")))))

;; ============================================================================
;; INCLUDE FILE NAVIGATION
;; ============================================================================

(defun tjp--include-at-point ()
  "Return the absolute path of the file `include'd on this line, or nil."
  (save-excursion
    (save-match-data
      (beginning-of-line)
      (when (re-search-forward "include[ \t]+\"\\([^\"]+\\)\"" (line-end-position) t)
        (expand-file-name (match-string-no-properties 1)
                          (if buffer-file-name
                              (file-name-directory buffer-file-name)
                            default-directory))))))

(defun tjp-find-include-at-point ()
  "Jump to the include file named on the current line.
Note that the search and the jump are kept apart: `save-excursion'
restores the current buffer as well as point, so visiting the file from
inside one would land you straight back where you started."
  (interactive)
  (let ((file (tjp--include-at-point)))
    (cond
     ((null file) (message "No include statement on current line"))
     ((file-exists-p file) (find-file file))
     (t (message "Include file not found: %s" file)))))

;; ============================================================================
;; DATE/TIME INSERTION HELPERS
;; ============================================================================

(defun tjp-insert-date ()
  "Insert current date in TaskJuggler format (YYYY-MM-DD)."
  (interactive)
  (insert (format-time-string "%Y-%m-%d")))

(defun tjp-insert-datetime ()
  "Insert current datetime in TaskJuggler format."
  (interactive)
  (insert (format-time-string "%Y-%m-%d-%H:%M")))

(defun tjp-insert-date-prompt ()
  "Prompt for and insert a date using org-mode's date picker if available."
  (interactive)
  (if (require 'org nil t)
      (let ((date (org-read-date nil nil nil "Select date: ")))
        (insert date))
    (call-interactively 'tjp-insert-date)))

;; ============================================================================
;; REPORT BUFFERS (structure, dependencies, allocation, statistics)
;; ============================================================================

(defvar tjp-nav-button-map
  (let ((map (make-sparse-keymap)))
    (define-key map [mouse-1] #'tjp--nav-button-action)
    (define-key map (kbd "RET") #'tjp--nav-button-action)
    map)
  "Keymap for clickable task links.")

(define-derived-mode tjp-report-mode special-mode "TJ Report"
  "Major mode for the TaskJuggler structure, dependency and statistics buffers."
  (setq-local truncate-lines t))

(defmacro tjp--with-report-buffer (name &rest body)
  "Erase the report buffer NAME, run BODY in it and display it read-only."
  (declare (indent 1) (debug (form body)))
  `(let ((buffer (get-buffer-create ,name)))
     (with-current-buffer buffer
       (unless (derived-mode-p 'tjp-report-mode) (tjp-report-mode))
       (let ((inhibit-read-only t))
         (erase-buffer)
         ,@body
         (goto-char (point-min))))
     (display-buffer buffer)
     buffer))

;; ============================================================================
;; HIERARCHICAL STRUCTURE BROWSER
;; ============================================================================

(defun tjp--make-clickable-definition (label line source-buffer)
  "Return LABEL as a link to LINE of SOURCE-BUFFER."
  (propertize label
              'face 'font-lock-function-name-face
              'mouse-face 'highlight
              'tjp-line line
              'tjp-source-buffer source-buffer
              'help-echo "mouse-1: jump to definition"
              'keymap tjp-nav-button-map))

(defun tjp--structure-tag (type)
  "Return the short label the structure browser uses for TYPE."
  (cond ((string= type "task") "task")
        ((string= type "resource") "res")
        ((string= type "account") "acct")
        ((string= type "macro") "macro")
        ((member type tjp--report-keywords) "report")
        (t type)))

(defun tjp-show-structure ()
  "Show the project structure in a side window with clickable links.
Definitions written without an ID are listed under their name."
  (interactive)
  (let ((source-buffer (current-buffer))
        (source-file (buffer-file-name))
        (entries '()))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward tjp--index-regexp nil t)
        (let* ((type (match-string-no-properties 1))
               (id (match-string-no-properties 2))
               (name (match-string-no-properties 3))
               (start (match-beginning 0)))
          (unless (tjp--in-string-or-comment-p start)
            (push (list (save-excursion (goto-char start) (current-indentation))
                        type id name
                        (line-number-at-pos start))
                  entries)))))
    (setq entries (nreverse entries))
    (let ((buffer (get-buffer-create "*TJ Structure*")))
      (with-current-buffer buffer
        (unless (derived-mode-p 'tjp-report-mode) (tjp-report-mode))
        (let ((inhibit-read-only t))
          (erase-buffer)
          (insert (format "TaskJuggler Structure: %s\n"
                          (if source-file (file-name-nondirectory source-file) "untitled")))
          (insert "Press RET or click to jump to a definition, q to quit.\n\n")
          (if (null entries)
              (insert "No definitions found in this file.\n")
            (dolist (entry entries)
              (cl-destructuring-bind (indent type id name line) entry
                (insert (make-string (/ indent tjp-indent-offset) ?\s))
                (insert (propertize (format "%-7s" (tjp--structure-tag type))
                                    'face 'font-lock-keyword-face))
                (insert (tjp--make-clickable-definition
                         (tjp--definition-label id name) line source-buffer))
                (insert (format "  %s%d\n"
                                (propertize ":" 'face 'shadow)
                                line)))))
          (goto-char (point-min))))
      (display-buffer buffer
                      '((display-buffer-in-side-window)
                        (side . right)
                        (window-width . 50)))
      buffer)))

;; ============================================================================
;; MACRO EXPANSION AND NAVIGATION
;; ============================================================================

(defun tjp--find-macro (name)
  "Return (START BODY-START BODY-END) for the macro called NAME, or nil.
The body runs to the first `]' that ends a line, which is how the tj3
scanner delimits it, so brackets inside the body do not cut it short."
  (save-excursion
    (save-match-data
      (goto-char (point-min))
      (when (re-search-forward
             (format "^[ \t]*macro[ \t]+%s[ \t]*\\[" (regexp-quote name))
             nil t)
        (let ((start (match-beginning 0))
              (body-start (point)))
          (list start body-start
                (if (re-search-forward "\\][ \t]*$" nil t)
                    (match-beginning 0)
                  (point-max))))))))

(defun tjp-expand-macro-at-point ()
  "Show the body of the macro named at point."
  (interactive)
  (let ((name (tjp--get-id-at-point)))
    (if (null name)
        (message "No macro at point")
      (let ((macro (tjp--find-macro name)))
        (if (null macro)
            (message "Macro definition not found: %s" name)
          (message "Macro %s expands to: %s" name
                   (string-trim (buffer-substring-no-properties
                                 (nth 1 macro) (nth 2 macro)))))))))

(defun tjp-find-macro-definition ()
  "Jump to the definition of the macro named at point."
  (interactive)
  (let ((name (tjp--get-id-at-point)))
    (if (null name)
        (message "No macro at point")
      (let ((macro (tjp--find-macro name)))
        (if macro
            (progn (push-mark) (goto-char (nth 0 macro)))
          (message "Macro not found: %s" name))))))

;; ============================================================================
;; DEPENDENCY VISUALIZATION
;; ============================================================================

(defun tjp--get-current-task ()
  "Get the ID of the current task context.
Searches backward from point to find the enclosing task definition."
  (save-excursion
    ;; Move to beginning of line to ensure we capture full task ID
    ;; even if point is in the middle of the task line
    (end-of-line)
    (when (re-search-backward "^\\s-*task\\s-+\\([a-zA-Z0-9_.]+\\)" nil t)
      (match-string-no-properties 1))))

(defun tjp--build-task-location-map ()
  "Build a hash table mapping task IDs to their line numbers.
Returns a hash table where keys are task IDs and values are line numbers.
Stores both the simple ID and the full hierarchical ID for each task."
  (let ((loc-map (make-hash-table :test 'equal))
        (id-stack '()))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward
              "^\\(\\s-*\\)task\\s-+\\([a-zA-Z0-9_.]+\\)"
              nil t)
        (let* ((indent (length (match-string 1)))
               (task-id (match-string-no-properties 2))
               (line (line-number-at-pos (match-beginning 0))))
          ;; Pop stack to find parent at lower indent level
          (while (and id-stack (>= (caar id-stack) indent))
            (pop id-stack))
          ;; Build hierarchical ID
          (let ((hier-id (if id-stack
                            (concat (cdar id-stack) "." task-id)
                          task-id)))
            ;; Store both simple and hierarchical IDs
            (puthash task-id line loc-map)
            (unless (string= task-id hier-id)
              (puthash hier-id line loc-map))
            ;; Push current task onto stack
            (push (cons indent hier-id) id-stack)))))
    loc-map))

(defun tjp--lookup-task-line (task-id loc-map)
  "Look up line number for TASK-ID in LOC-MAP.
Tries exact match first, then tries matching the last component
of hierarchical IDs."
  (or (gethash task-id loc-map)
      ;; Try matching just the last component (simple ID)
      (let ((simple-id (car (last (split-string task-id "\\.")))))
        (gethash simple-id loc-map))
      ;; Try finding any key that ends with this ID
      (let ((found nil))
        (maphash (lambda (key val)
                   (when (and (not found)
                              (or (string-suffix-p (concat "." task-id) key)
                                  (string= task-id key)))
                     (setq found val)))
                 loc-map)
        found)))

(defun tjp--make-clickable-task (task-id line source-buffer)
  "Create a clickable text for TASK-ID at LINE in SOURCE-BUFFER."
  (propertize (format "%s:%d" task-id line)
              'face 'font-lock-function-name-face
              'mouse-face 'highlight
              'tjp-task-id task-id
              'tjp-line line
              'tjp-source-buffer source-buffer
              'help-echo "mouse-1: jump to task definition"
              'keymap tjp-nav-button-map))

(defun tjp--nav-button-action (&optional event)
  "Jump to the task definition at point or mouse EVENT."
  (interactive (list last-input-event))
  (when event
    (mouse-set-point event))
  (let ((source-buffer (get-text-property (point) 'tjp-source-buffer))
        (line (get-text-property (point) 'tjp-line)))
    (when (and source-buffer line)
      (pop-to-buffer source-buffer)
      (goto-char (point-min))
      (forward-line (1- line))
      (back-to-indentation))))

(defun tjp--build-dependency-map ()
  "Build a hash table mapping task IDs to their direct dependencies.
Returns a hash table where keys are task IDs and values are lists
of dependency IDs. Note: the `!' prefix in TaskJuggler indicates
relative task references, not dependency type."
  (let ((deps-map (make-hash-table :test 'equal)))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward
              "depends\\s-+\\([a-zA-Z0-9_.!, {}]+\\)"
              nil t)
        (let ((deps-string (match-string 1))
              (task (tjp--get-current-task)))
          (when task
            ;; Handle comma-separated dependencies, strip modifiers like { gapduration 2d }
            (let ((clean-deps (replace-regexp-in-string "{[^}]*}" "" deps-string)))
              (dolist (dep (split-string clean-deps "[,]" t "\\s-*"))
                (let* ((dep-clean (string-trim dep))
                       ;; Remove ! prefix (relative reference) to get base ID
                       (dep-id (replace-regexp-in-string "^!+" "" dep-clean)))
                  (when (not (string-empty-p dep-id))
                    (push dep-id (gethash task deps-map))))))))))
    deps-map))

(defun tjp--get-dependency-chain (task deps-map visited)
  "Recursively get the dependency chain for TASK.
DEPS-MAP is the hash table of dependencies.
VISITED is a list of already-visited tasks (to detect cycles).
Returns a nested list structure representing the dependency tree."
  (if (member task visited)
      (list task "(cycle detected)")
    (let ((deps (gethash task deps-map)))
      (if deps
          (cons task
                (mapcar (lambda (dep-id)
                          (tjp--get-dependency-chain
                           dep-id deps-map (cons task visited)))
                        deps))
        (list task)))))

(defun tjp--insert-dependency-tree (tree indent loc-map source-buffer)
  "Insert TREE into current buffer with proper indentation.
INDENT is the current indentation level.
LOC-MAP maps task IDs to line numbers.
SOURCE-BUFFER is the original TJP buffer for navigation."
  (let ((task (car tree))
        (deps (cdr tree))
        (prefix (make-string (* indent 2) ?\s)))
    ;; Insert task with clickable link
    (let ((line (tjp--lookup-task-line task loc-map)))
      (insert prefix)
      (if line
          (insert (tjp--make-clickable-task task line source-buffer))
        (insert (propertize task 'face 'font-lock-function-name-face)))
      (insert "\n"))
    ;; Insert dependencies
    (dolist (dep deps)
      (if (stringp dep)
          ;; Cycle detected marker
          (insert (format "%s  %s\n" prefix
                         (propertize dep 'face 'font-lock-warning-face)))
        ;; dep is a subtree (list starting with task id)
        (insert (format "%s  └── " prefix))
        ;; Insert subtree inline (remove leading whitespace from first line)
        (let ((start (point)))
          (tjp--insert-dependency-tree dep (+ indent 2) loc-map source-buffer)
          ;; Remove the extra indentation from first line of subtree
          (save-excursion
            (goto-char start)
            (when (looking-at (make-string (* (+ indent 2) 2) ?\s))
              (delete-char (* (+ indent 2) 2)))))))))

(defun tjp-show-dependencies ()
  "Show the full dependency chain for the task at point."
  (interactive)
  (let ((current-task (tjp--get-current-task))
        (source-buffer (current-buffer))
        (source-file (buffer-file-name)))

    (if (not current-task)
        (message "No task found at point")

      (let* ((deps-buffer (get-buffer-create "*TJ Dependencies*"))
             (deps-map (tjp--build-dependency-map))
             (loc-map (tjp--build-task-location-map))
             (chain (tjp--get-dependency-chain current-task deps-map nil)))

        (with-current-buffer deps-buffer
          (unless (derived-mode-p 'tjp-report-mode) (tjp-report-mode))
          (let ((inhibit-read-only t))
          (erase-buffer)
          (insert (format "Dependency Chain - %s\n"
                         (if source-file (file-name-nondirectory source-file) "untitled")))
          (insert "=====================================\n\n")

          (if (null (cdr chain))
              (let ((line (tjp--lookup-task-line current-task loc-map)))
                (if line
                    (insert (tjp--make-clickable-task current-task line source-buffer))
                  (insert (propertize current-task 'face 'font-lock-function-name-face)))
                (insert " has no dependencies.\n"))
            (tjp--insert-dependency-tree chain 0 loc-map source-buffer))

          (insert "\nPress RET or click on a task to jump to its definition.\n")
          (goto-char (point-min))))

        (display-buffer deps-buffer)))))

;; ============================================================================
;; RESOURCE ALLOCATION DISPLAY
;; ============================================================================

(defun tjp-show-resource-allocation ()
  "Show resource allocation summary."
  (interactive)
  (let ((alloc-buffer (get-buffer-create "*TJ Resource Allocation*"))
        (allocations (make-hash-table :test 'equal))
        (source-file (buffer-file-name)))

    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward
              "allocate\\s-+\\([a-zA-Z0-9_.]+\\)"
              nil t)
        (let ((resource (match-string 1))
              (task (tjp--get-current-task)))
          (when task
            (push task (gethash resource allocations))))))

    (with-current-buffer alloc-buffer
      (unless (derived-mode-p 'tjp-report-mode) (tjp-report-mode))
      (let ((inhibit-read-only t))
      (erase-buffer)
      (insert (format "Resource Allocations - %s\n"
                     (if source-file (file-name-nondirectory source-file) "untitled")))
      (insert "=====================================\n\n")

      (if (zerop (hash-table-count allocations))
          (insert "No resource allocations found in this file.\n")
        (maphash (lambda (resource tasks)
                   (insert (format "%s is allocated to:\n"
                                 (propertize resource 'face 'font-lock-variable-name-face)))
                   (dolist (task tasks)
                     (insert (format "  - %s\n"
                                   (propertize task 'face 'font-lock-function-name-face))))
                   (insert "\n"))
                 allocations))

      (goto-char (point-min))))

    (display-buffer alloc-buffer)))

;; ============================================================================
;; LIVE SYNTAX VALIDATION
;; ============================================================================

(defun tjp-validate-buffer ()
  "Check the project's syntax with tj3.
Runs asynchronously in a compilation buffer, so errors are clickable and
Emacs stays responsive."
  (interactive)
  (let ((command (tjp--build-command "--check-syntax")))
    (tjp--save-project-buffers)
    (tjp--run command (lambda (_mode) "*TJ Validation*"))))

(defun tjp-validate-on-save ()
  "Validate buffer on save if `tjp-auto-validate' is non-nil."
  (when tjp-auto-validate
    (tjp-validate-buffer)))

;; ============================================================================
;; PROJECT STATISTICS
;; ============================================================================

(defconst tjp--effort-regexp
  "^[ \t]*effort[ \t]+\\([0-9.]+\\)[ \t]*\\(min\\|[hdwmy]\\)\\_>"
  "Regexp matching an `effort' attribute and its unit.")

(defun tjp--project-number (keyword default)
  "Return the number given to project attribute KEYWORD, or DEFAULT."
  (save-excursion
    (goto-char (point-min))
    (if (re-search-forward
         (format "^[ \t]*%s[ \t]+\\([0-9.]+\\)" (regexp-quote keyword)) nil t)
        (string-to-number (match-string 1))
      default)))

(defun tjp--effort-days (value unit hours-per-day days-per-year)
  "Convert VALUE of UNIT into working days.
tj3 derives all effort units from `dailyworkinghours' (HOURS-PER-DAY) and
`yearlyworkingdays' (DAYS-PER-YEAR); the same factors are used here."
  (pcase unit
    ("min" (/ value 60.0 hours-per-day))
    ("h" (/ value hours-per-day))
    ("d" value)
    ("w" (* value (/ days-per-year 52.1428)))
    ("m" (* value (/ days-per-year 12.0)))
    ("y" (* value days-per-year))
    (_ 0.0)))

(defun tjp--count-matches (regexp)
  "Count matches of REGEXP outside strings and comments."
  (let ((count 0))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward regexp nil t)
        (unless (tjp--in-string-or-comment-p (match-beginning 0))
          (setq count (1+ count)))))
    count))

(defun tjp-show-statistics ()
  "Show a rough size estimate for the project in this buffer."
  (interactive)
  (let* ((source-file (buffer-file-name))
         (hours-per-day (tjp--project-number "dailyworkinghours" 8.0))
         (days-per-year (tjp--project-number "yearlyworkingdays" 260.714))
         (days-per-week (/ days-per-year 52.1428))
         (days-per-month (/ days-per-year 12.0))
         (counts (list (cons "Tasks" 0) (cons "Resources" 0) (cons "Accounts" 0)
                       (cons "Macros" 0) (cons "Reports" 0)))
         (milestones (tjp--count-matches "^[ \t]*milestone\\_>"))
         (total-effort 0.0))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward tjp--index-regexp nil t)
        (let ((type (match-string-no-properties 1)))
          (unless (tjp--in-string-or-comment-p (match-beginning 0))
            (let ((key (cond ((string= type "task") "Tasks")
                             ((string= type "resource") "Resources")
                             ((string= type "account") "Accounts")
                             ((string= type "macro") "Macros")
                             ((member type tjp--report-keywords) "Reports"))))
              (when key
                (cl-incf (cdr (assoc key counts))))))))
      (goto-char (point-min))
      (while (re-search-forward tjp--effort-regexp nil t)
        (unless (tjp--in-string-or-comment-p (match-beginning 0))
          (setq total-effort
                (+ total-effort
                   (tjp--effort-days (string-to-number (match-string 1))
                                     (match-string 2)
                                     hours-per-day days-per-year))))))
    (tjp--with-report-buffer "*TJ Statistics*"
      (insert "Project Statistics\n")
      (insert (format "File: %s\n\n"
                      (if source-file (file-name-nondirectory source-file) "untitled")))
      (insert "=====================================\n\n")
      (dolist (entry counts)
        (insert (format "%-20s %6d\n" (concat (car entry) ":") (cdr entry))))
      (insert (format "%-20s %6d\n" "Milestones:" milestones))
      (insert "\n")
      (insert (format "%-20s %6.1f days\n" "Total effort:" total-effort))
      (insert (format "%-20s %6.1f weeks\n" "" (/ total-effort days-per-week)))
      (insert (format "%-20s %6.1f months\n" "" (/ total-effort days-per-month)))
      (insert "\n")
      (insert (format "Estimated from the `effort' attributes in this file only,\n"))
      (insert (format "at %g working hours per day and %g working days per year.\n"
                      hours-per-day days-per-year)))))

;; ============================================================================
;; OUTLINE MODE INTEGRATION
;; ============================================================================

(defun tjp-setup-outline ()
  "Setup outline-mode patterns for TaskJuggler."
  (setq-local outline-regexp
              (concat "^\\s-*\\("
                     (regexp-opt '("project" "task" "resource" 
                                  "account" "report" "scenario" "macro"))
                     "\\)"))
  (setq-local outline-level
              (lambda ()
                (save-excursion
                  (looking-at outline-regexp)
                  (1+ (/ (current-indentation) tjp-indent-offset))))))

;; ============================================================================
;; NAVIGATION HELPERS
;; ============================================================================

(defconst tjp--block-motion-regexp
  (concat "^[ \t]*\\(" (regexp-opt tjp-structural-keywords) "\\)[ \t]+")
  "Regexp matching the start of a property definition, for block motion.")

(defun tjp--goto-block (direction)
  "Move to the next definition in DIRECTION, which is 1 or -1.
Returns non-nil when point moved."
  (let ((search (if (> direction 0) #'re-search-forward #'re-search-backward))
        (start (point))
        (found nil))
    (if (> direction 0) (end-of-line) (beginning-of-line))
    (while (and (not found)
                (funcall search tjp--block-motion-regexp nil t))
      (if (tjp--in-string-or-comment-p (match-beginning 1))
          nil
        (setq found (match-beginning 1))))
    (if found
        (progn (goto-char found) (back-to-indentation) t)
      (goto-char start)
      nil)))

(defun tjp-next-block ()
  "Move to the next task/resource/report definition."
  (interactive)
  (unless (tjp--goto-block 1)
    (message "No more blocks")))

(defun tjp-previous-block ()
  "Move to the previous task/resource/report definition."
  (interactive)
  (unless (tjp--goto-block -1)
    (message "No previous blocks")))

;; ============================================================================
;; COMPILATION SUPPORT
;; ============================================================================

(defvar-local tjp--auto-compile-command nil
  "The `compile-command' this mode computed, used to detect user overrides.")

(defun tjp--compile-target ()
  "Return the .tjp file tj3 should be run on, or signal a user error.
tj3 refuses any input file that does not end in `.tjp', so an include
file has to name its master project in `tjp-project-file'."
  (let ((file (tjp--project-file)))
    (cond
     ((null file)
      (user-error "Buffer is not visiting a file; save it first"))
     ((not (string-suffix-p ".tjp" file))
      (user-error "tj3 only accepts a .tjp file: set `tjp-project-file' to the master project of %s"
                  (file-name-nondirectory file)))
     ((not (file-exists-p file))
      (user-error "Project file does not exist: %s" file))
     (t file))))

(defun tjp--compiler ()
  "Return the absolute path of the tj3 executable, or signal a user error."
  (or (tjp--resolve-command tjp-compiler-command)
      (user-error "Cannot find `%s'.  Set `tjp-compiler-command' to its absolute path"
                  tjp-compiler-command)))

(defun tjp--build-command (&rest args)
  "Return a shell command running tj3 with ARGS on the project file."
  ;; Resolve the target first: "this buffer has no file" is a more useful
  ;; complaint than "I cannot find tj3".
  (let ((target (tjp--compile-target)))
    (mapconcat #'shell-quote-argument
               (append (list (tjp--compiler) "--silent" "--no-color")
                       args
                       (list target))
               " ")))

(defun tjp--effective-compile-command ()
  "Return the command `tjp-compile' should run.
A `compile-command' set by the user or by `.dir-locals.el' wins; otherwise
the command is derived from `tjp-compiler-command' and the project file."
  (if (and tjp--auto-compile-command
           (not (equal compile-command tjp--auto-compile-command)))
      compile-command
    (let ((command (tjp--build-command)))
      (setq tjp--auto-compile-command command)
      (setq-local compile-command command)
      command)))

(defun tjp--save-project-buffers ()
  "Save every modified TaskJuggler buffer, since tj3 reads includes from disk."
  (save-some-buffers t (lambda () (derived-mode-p 'tjp-mode))))

(defun tjp--run (command &optional name-function)
  "Run COMMAND in a compilation buffer rooted at the project directory.
NAME-FUNCTION, if given, names the buffer as for `compilation-start'."
  (let ((default-directory (file-name-directory (tjp--compile-target))))
    (compilation-start command nil name-function)))

(defun tjp-compile ()
  "Compile the current TaskJuggler project with tj3."
  (interactive)
  ;; Resolve the target before saving: a buffer without a file must not be
  ;; turned into a "where should I save this?" prompt.
  (let ((command (tjp--effective-compile-command)))
    (tjp--save-project-buffers)
    (tjp--run command)))

(defun tjp--project-files ()
  "Return every file of the project, master first, following `include's."
  (let ((visited (make-hash-table :test 'equal))
        (files '()))
    (cl-labels ((walk (file)
                  (let ((abs (and file (file-truename file))))
                    (when (and file (file-readable-p file) (not (gethash abs visited)))
                      (puthash abs t visited)
                      (push file files)
                      (mapc #'walk (cdr (tjp--scan-file file)))))))
      (walk (tjp--project-file)))
    (nreverse files)))

(defun tjp--output-dir ()
  "Return the directory tj3 writes reports into.
Honours a project-level `outputdir', defaulting to the project directory."
  (let* ((project (or (tjp--project-file) (buffer-file-name)))
         (base (if project (file-name-directory project) default-directory))
         (dir base))
    (catch 'found
      (dolist (file (tjp--project-files) dir)
        (with-temp-buffer
          (tjp--prepare-scan-buffer)
          (insert-file-contents file)
          (goto-char (point-min))
          (when (re-search-forward "^[ \t]*outputdir[ \t]+\"\\([^\"]+\\)\"" nil t)
            (throw 'found
                   (file-name-as-directory
                    (expand-file-name (match-string-no-properties 1) base)))))))))

(defconst tjp--report-header-regexp
  (concat "^[ \t]*\\(" (regexp-opt tjp--report-keywords) "\\)[ \t]+"
          ;; `report [<id>] <name>': the ID is optional, the name is not, and
          ;; it is the name - not the ID - that becomes the output file name.
          "\\(?:\\([A-Za-z_][A-Za-z0-9_]*\\)[ \t]+\\)?"
          "\"\\([^\"]*\\)\"[ \t]*{")
  "Regexp matching a report definition that opens a block.
Group 1 is the report type, group 2 the optional ID, group 3 the name.")

(defun tjp--block-declares-html-p (open-brace)
  "Return non-nil if the block whose `{' is at OPEN-BRACE asks for HTML output."
  (save-excursion
    (let ((end (ignore-errors (scan-lists open-brace 1 0))))
      (goto-char (1+ open-brace))
      (and end
           (re-search-forward "^[ \t]*formats[ \t]+\\([^\n}]*\\)" end t)
           (string-match-p "\\_<html\\_>" (match-string-no-properties 1))))))

(defun tjp--scan-reports-in-buffer (file)
  "Return the HTML reports defined in the current buffer.
Each entry is (TYPE ID NAME FILE)."
  (let ((reports '()))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward tjp--report-header-regexp nil t)
        (let ((type (match-string-no-properties 1))
              (id (match-string-no-properties 2))
              (name (match-string-no-properties 3))
              (brace (1- (match-end 0))))
          (when (and (not (tjp--in-string-or-comment-p (match-beginning 0)))
                     (tjp--block-declares-html-p brace))
            (push (list type id name file) reports)))))
    (nreverse reports)))

(defun tjp--html-reports ()
  "Return every report in the project that generates HTML output."
  (let ((reports '()))
    (dolist (file (tjp--project-files) (nreverse reports))
      (let ((buffer (find-buffer-visiting file)))
        (dolist (report (if buffer
                            (with-current-buffer buffer
                              (tjp--scan-reports-in-buffer file))
                          (with-temp-buffer
                            (tjp--prepare-scan-buffer)
                            (insert-file-contents file)
                            (tjp--scan-reports-in-buffer file))))
          (push report reports))))))

(defun tjp--report-output-file (report)
  "Return the file tj3 writes REPORT to.
A report name that starts with a slash is an absolute file name; every
other name is relative to the project's `outputdir'."
  (let ((name (nth 2 report)))
    (concat (if (file-name-absolute-p name)
                name
              (expand-file-name name (tjp--output-dir)))
            ".html")))

(defun tjp--read-report (reports)
  "Ask the user to pick one of REPORTS."
  (let* ((choices (mapcar (lambda (r)
                            (cons (format "%s %s(%s)"
                                          (nth 0 r)
                                          (if (nth 1 r) (concat (nth 1 r) " ") "")
                                          (nth 2 r))
                                  r))
                          reports))
         (choice (completing-read "Report: " choices nil t)))
    (cdr (assoc choice choices))))

(defun tjp--compile-then (command callback)
  "Run COMMAND with `compile' and call CALLBACK once it finishes successfully."
  (let (finish-fn)
    (setq finish-fn
          (lambda (buffer status)
            (remove-hook 'compilation-finish-functions finish-fn)
            (when (and (buffer-live-p buffer)
                       (string-match-p "finished" status))
              (funcall callback))))
    (add-hook 'compilation-finish-functions finish-fn)
    (tjp--run command)))

(defun tjp-compile-and-view ()
  "Compile the project and open a report's HTML output.
The output file name comes from the report's name - the quoted string,
which is what tj3 uses as the base name - and the project's `outputdir'.
When the project defines more than one HTML report you are asked which
one to open.  The file is opened only after compilation succeeds."
  (interactive)
  (let* ((command (tjp--effective-compile-command))
         (reports (tjp--html-reports))
         (report (cond
                  ((null reports)
                   (user-error "No report with `formats html' found in this project"))
                  ((null (cdr reports)) (car reports))
                  (t (tjp--read-report reports))))
         (html-file (tjp--report-output-file report)))
    (tjp--save-project-buffers)
    (tjp--compile-then
     command
     (lambda ()
       (if (file-exists-p html-file)
           (browse-url-of-file html-file)
         (message "Report output not found: %s" html-file))))))

;; ============================================================================
;; HELPER FUNCTIONS
;; ============================================================================

(defcustom tjp-cleanup-whitespace-on-save t
  "When non-nil, delete trailing whitespace from the buffer on save.
Whitespace inside a multi-line string is never touched: there it is part
of the value tj3 reads."
  :type 'boolean
  :group 'tjp)

(defun tjp-cleanup-whitespace ()
  "Delete trailing whitespace outside strings, if enabled.
See `tjp-cleanup-whitespace-on-save'."
  (when (and (derived-mode-p 'tjp-mode) tjp-cleanup-whitespace-on-save)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "[ \t]+$" nil t)
        (unless (tjp--in-string-p (match-beginning 0))
          (delete-region (match-beginning 0) (match-end 0)))))))

(defun tjp--prepare-insertion-point ()
  "Move point onto a clean line ready to receive a new block.
If the current line already has content, open a fresh line just below the
enclosing statement.  Returns the column the new block should start at,
derived from the current brace-nesting depth so the block nests correctly
inside the surrounding task/resource/report."
  (let ((depth (tjp--nesting-depth (line-beginning-position))))
    (if (save-excursion (beginning-of-line) (looking-at-p "[ \t]*$"))
        ;; Reuse the current blank line, clearing any stray whitespace.
        (progn (beginning-of-line)
               (delete-region (point) (line-end-position)))
      ;; Otherwise open a fresh line after the current statement.
      (end-of-line)
      (newline))
    (* (max 0 depth) tjp-indent-offset)))

(defun tjp--insert-block (header body-lines)
  "Insert a TaskJuggler block at point and leave point inside it.
HEADER is the text before the opening brace (e.g. \"task foo \\\"Foo\\\"\").
BODY-LINES is a list of strings placed inside the block; when nil a single
empty, indented line is left for the user to type on.  Point ends at the end
of the first body line."
  (let* ((indent (tjp--prepare-insertion-point))
         (pad (make-string indent ?\s))
         (ipad (make-string (+ indent tjp-indent-offset) ?\s))
         (lines (or body-lines '("")))
         body-start)
    (insert pad header " {\n")
    (setq body-start (point))
    (dolist (line lines)
      (insert ipad line "\n"))
    (insert pad "}\n")
    (goto-char body-start)
    (end-of-line)))

(defun tjp--read-name (prompt)
  "Read a non-empty name with PROMPT.
TaskJuggler makes the name mandatory and the ID optional, not the other
way round: `task \"Design\" { ... }' is valid, `task design { ... }' is
not."
  (let ((name ""))
    (while (string-empty-p (setq name (string-trim (read-string prompt))))
      (minibuffer-message "A name is required"))
    name))

(defun tjp--block-header (keyword id name)
  "Build a block header string for KEYWORD with optional ID and NAME."
  (if (or (null id) (string-empty-p id))
      (format "%s \"%s\"" keyword name)
    (format "%s %s \"%s\"" keyword id name)))

(defun tjp-insert-task ()
  "Insert a task at point, nested correctly inside any enclosing block."
  (interactive)
  (let* ((name (tjp--read-name "Task name: "))
         (id (string-trim (read-string "Task ID (optional): "))))
    (tjp--insert-block (tjp--block-header "task" id name) nil)))

(defun tjp-insert-resource ()
  "Insert a resource at point, nested correctly inside any enclosing block."
  (interactive)
  (let* ((name (tjp--read-name "Resource name: "))
         (id (string-trim (read-string "Resource ID (optional): "))))
    (tjp--insert-block (tjp--block-header "resource" id name) nil)))

(defun tjp-insert-report ()
  "Insert a report at point, choosing the type and seeding sensible defaults."
  (interactive)
  (let* ((type (completing-read
                "Report type: "
                tjp--report-keywords nil t nil nil "taskreport"))
         ;; The report name is what tj3 uses as the base name of the output
         ;; file, so "Project Overview" produces "Project Overview.html".
         (name (tjp--read-name "Report name (becomes the output file name): "))
         (id (string-trim (read-string "Report ID (optional): ")))
         (body (pcase type
                 ("taskreport"
                  '("formats html"
                    "columns name, start, end, effort, chart"
                    "loadunit days"))
                 ("resourcereport"
                  '("formats html"
                    "columns name, effort"
                    "loadunit days"))
                 ("accountreport"
                  '("formats html"
                    "columns name, total"))
                 ("textreport"
                  '("formats html"
                    "text \"\""))
                 ("export"
                  '("formats tjp"))
                 (_
                  '("formats html")))))
    (tjp--insert-block (tjp--block-header type id name) body)))

;; ============================================================================
;; KEYMAP
;; ============================================================================

(defalias 'tjp-xref-go-back
  (if (fboundp 'xref-go-back) 'xref-go-back 'xref-pop-marker-stack)
  "Return to the position `xref-find-definitions' was invoked from.
`xref-pop-marker-stack' is obsolete since Emacs 29.1; this picks
whichever command the running Emacs provides.")

(defvar tjp-mode-map
  (let ((map (make-sparse-keymap)))
    ;; Compilation
    (define-key map (kbd "C-c C-c") 'tjp-compile)
    (define-key map (kbd "C-c C-v") 'tjp-compile-and-view)
    (define-key map (kbd "C-c C-k") 'tjp-validate-buffer)

    ;; Navigation
    (define-key map (kbd "C-c C-n") 'tjp-next-block)
    (define-key map (kbd "C-c C-p") 'tjp-previous-block)
    (define-key map (kbd "C-c C-j") 'tjp-find-include-at-point)
    (define-key map (kbd "M-.") 'xref-find-definitions)
    (define-key map (kbd "M-,") 'tjp-xref-go-back)

    ;; Folding
    (define-key map (kbd "C-c C-f") 'tjp-toggle-fold)
    (define-key map (kbd "C-c C-a") 'tjp-fold-all)
    (define-key map (kbd "C-c C-o") 'tjp-unfold-all)

    ;; Templates
    (define-key map (kbd "C-c C-i") 'tjp-insert-task)
    (define-key map (kbd "C-c C-r") 'tjp-insert-resource)
    (define-key map (kbd "C-c C-R") 'tjp-insert-report)
    (define-key map (kbd "C-c C-d") 'tjp-insert-date-prompt)

    ;; Structure and Analysis
    (define-key map (kbd "C-c C-s") 'tjp-show-structure)
    (define-key map (kbd "C-c C-=") 'tjp-show-statistics)

    ;; Tags
    (define-key map (kbd "C-c C-t") 'tjp-generate-tags)

    ;; Documentation
    (define-key map (kbd "C-c C-h") 'tjp-show-help)

    ;; Analysis
    (define-key map (kbd "C-c C-y") 'tjp-show-dependencies)
    (define-key map (kbd "C-c C-l") 'tjp-show-resource-allocation)

    map)
  "Keymap for TaskJuggler mode.")

;; ============================================================================
;; MODE DEFINITION
;; ============================================================================

;;;###autoload
(define-derived-mode tjp-mode prog-mode "TJP"
  "Major mode for editing TaskJuggler project files.

Key bindings:
\\{tjp-mode-map}"
  :syntax-table tjp-mode-syntax-table

  ;; Font locking
  (setq-local font-lock-defaults '(tjp-font-lock-keywords nil nil))

  ;; Comments
  (setq-local comment-start "# ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "\\(?:#+\\|//+\\)[ \t]*")

  ;; Multi-line strings and macro bodies need syntax properties: see
  ;; `tjp-syntax-propertize'.
  (setq-local syntax-propertize-function #'tjp-syntax-propertize)
  (setq-local parse-sexp-lookup-properties t)

  ;; Indentation
  (setq-local indent-line-function 'tjp-indent-line)
  (setq-local electric-indent-chars
              (append "{}[]" (default-value 'electric-indent-chars)))

  ;; Compilation.  This is a plausible default that also serves as the marker
  ;; for "the user has not overridden `compile-command'"; `tjp-compile'
  ;; recomputes it from the resolved tj3 path and `tjp-project-file'.
  (setq tjp--auto-compile-command
        (concat tjp-compiler-command " --silent "
                (if buffer-file-name
                    (shell-quote-argument buffer-file-name)
                  "")))
  (setq-local compile-command tjp--auto-compile-command)

  ;; Enhanced error navigation
  (tjp-setup-compilation)

  ;; Folding support - use hideshow for brace-aware folding
  (tjp-setup-hideshow)
  (hs-minor-mode 1)

  ;; Xref backend
  (add-hook 'xref-backend-functions #'tjp-xref-backend nil t)

  ;; Imenu
  (setq-local imenu-create-index-function #'tjp--imenu-create-index)

  ;; Eldoc.  `eldoc-documentation-functions' is the documented hook; the
  ;; old `eldoc-documentation-function' is an alias for the display
  ;; *strategy* since Emacs 28, so advising it would override the user's
  ;; choice and mask every other eldoc backend.
  (add-hook 'eldoc-documentation-functions #'tjp-eldoc-function nil t)
  (eldoc-mode 1)

  ;; Completion at point
  (add-hook 'completion-at-point-functions #'tjp-completion-at-point nil t)

  ;; Cleanup whitespace on save
  (add-hook 'before-save-hook 'tjp-cleanup-whitespace nil t)

  ;; Auto-validation.  The hook itself checks `tjp-auto-validate', so
  ;; toggling the option takes effect without reopening the file.
  (add-hook 'after-save-hook 'tjp-validate-on-save nil t)

  ;; Outline mode setup
  (tjp-setup-outline)

  ;; Try to setup optional features
  (tjp-setup-flycheck))

;; ============================================================================
;; FILE ASSOCIATION
;; ============================================================================

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.tjp\\'" . tjp-mode))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.tji\\'" . tjp-mode))

;; ============================================================================
;; OPTIONAL INTEGRATIONS
;; ============================================================================

;; Projectile: treat a directory that holds project.tjp as a project root.
(with-eval-after-load 'projectile
  (add-to-list 'projectile-project-root-files "project.tjp"))

;; Skeleton for new .tjp files.  This only fires for users who have
;; enabled `auto-insert-mode'; the result compiles with tj3 as it stands,
;; which needs a project, a resource, a task and a named report.
(with-eval-after-load 'autoinsert
  (define-auto-insert
    '("\\.tjp\\'" . "TaskJuggler Project Template")
    '("Project ID: "
      "project " str " \"" (read-string "Project title: ") "\" "
      (format-time-string "%Y-%m-%d") " - "
      (format-time-string "%Y-%m-%d" (time-add (current-time) (days-to-time 365))) " {\n"
      "  timezone \"UTC\"\n"
      "  timeformat \"%Y-%m-%d\"\n"
      "  currency \"USD\"\n"
      "}\n"
      "\n"
      "# Resources\n"
      "resource me \"" (user-full-name) "\"\n"
      "\n"
      "# Tasks\n"
      "task start \"Get started\" {\n"
      "  effort 1d\n"
      "  allocate me\n"
      "}\n"
      "\n"
      "# Reports\n"
      ;; The quoted name - not the ID - is the base name of the generated
      ;; file, so this report is written to "Project Overview.html".
      "taskreport overview \"Project Overview\" {\n"
      "  formats html\n"
      "  columns name, start, end, effort, chart\n"
      "  loadunit days\n"
      "  hideresource 1\n"
      "}\n")))

;; Evil / Doom / Spacemacs keybindings.  Soft require: a single-file
;; installation of tjp-mode.el alone still works, it just has no evil
;; layer.  `tjp-evil' itself is inert unless evil is loaded.
(require 'tjp-evil nil t)

(provide 'tjp-mode)

;;; tjp-mode.el ends here
